# Generated by Django 3.0.3 on 2026-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='subject',
            field=models.CharField(default='通用', help_text='例如：计算机网络、数据结构、数学', max_length=50, verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='fill',
            name='subject',
            field=models.CharField(default='通用', max_length=50, verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='judge',
            name='subject',
            field=models.CharField(default='通用', max_length=50, verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='subjective',
            name='subject',
            field=models.CharField(default='通用', max_length=50, verbose_name='所属科目'),
        ),
    ]
