# Generated by Django 3.0.3 on 2026-05-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0003_auto_20260503_1458'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '待审核'), ('1', '已通过'), ('2', '已拒绝')], default='0', max_length=1, verbose_name='状态')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['-apply_time'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='准考证号')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='准考证PDF文件')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration', verbose_name='报名记录')),
            ],
            options={
                'verbose_name': '准考证',
                'verbose_name_plural': '准考证',
                'ordering': ['-generate_time'],
            },
        ),
    ]
