# Generated by Codex on 2026-06-07

from django.db import migrations, models
import django.db.models.deletion


CREATE_STUDENT_PROFILE_TABLE = """
CREATE TABLE IF NOT EXISTS "user_studentprofile" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "avatar" varchar(255) NOT NULL,
    "update_time" datetime NOT NULL,
    "student_id" integer NOT NULL UNIQUE
        REFERENCES "user_student" ("id") DEFERRABLE INITIALLY DEFERRED
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_STUDENT_PROFILE_TABLE, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='StudentProfile',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('avatar', models.CharField(blank=True, default='', max_length=255, verbose_name='头像地址')),
                        ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                        ('student', models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='profile',
                            to='user.Student',
                            verbose_name='学生'
                        )),
                    ],
                    options={
                        'verbose_name': '学生扩展资料',
                        'verbose_name_plural': '学生扩展资料',
                        'ordering': ['id'],
                    },
                ),
            ],
        ),
    ]
