# Generated by Django 3.0.3 on 2026-05-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20230626_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectiveanswer',
            options={'ordering': ['id'], 'verbose_name': '主观题批改', 'verbose_name_plural': '主观题批改'},
        ),
    ]
