# Generated by Django 3.0.3 on 2026-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('exam', '0002_auto_20230626_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectiveanswer',
            options={'ordering': ['id'], 'verbose_name': '主观题批改', 'verbose_name_plural': '主观题批改'},
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, choices=[('qualification', '资质认证'), ('course', '课程考试'), ('competition', '竞赛选拔'), ('other', '其他')], default='other', max_length=20, null=True, verbose_name='考试类别'),
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.CharField(default='通用', help_text='填写与题目科目一致的名称，抽题时按此科目过滤', max_length=50, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='clazzs',
            field=models.ManyToManyField(blank=True, help_text='留空表示所有学生均可报名；选择班级则仅限该班级学生', to='user.Clazz', verbose_name='限定班级'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='major',
            field=models.CharField(default='', help_text='可填写适用专业，留空表示不限专业', max_length=50, verbose_name='专业方向'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='考试名称'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_time',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='试卷名称'),
        ),
    ]
