# Generated by Codex on 2026-06-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('exam', '0003_auto_20260503_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='准考证号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试报名',
                'verbose_name_plural': '考试报名',
                'ordering': ['-create_time'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
