# Generated by Codex on 2026-06-07

from django.db import migrations, models
import django.db.models.deletion


CREATE_HISTORY_TABLE = """
CREATE TABLE IF NOT EXISTS "exam_subjectivereviewhistory" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "operator" varchar(50) NOT NULL,
    "old_score" smallint unsigned NULL CHECK ("old_score" >= 0),
    "new_score" smallint unsigned NULL CHECK ("new_score" >= 0),
    "old_comment" text NOT NULL,
    "new_comment" text NOT NULL,
    "create_time" datetime NOT NULL,
    "subjective_answer_id" integer NOT NULL
        REFERENCES "exam_subjectiveanswer" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "exam_review_history_answer_idx"
    ON "exam_subjectivereviewhistory" ("subjective_answer_id");
"""


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_registration_ai_review'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_HISTORY_TABLE, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='SubjectiveReviewHistory',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('operator', models.CharField(default='', max_length=50, verbose_name='操作人')),
                        ('old_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='变更前分值')),
                        ('new_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='变更后分值')),
                        ('old_comment', models.TextField(blank=True, default='', verbose_name='变更前评语')),
                        ('new_comment', models.TextField(blank=True, default='', verbose_name='变更后评语')),
                        ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                        ('subjective_answer', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='histories',
                            to='exam.SubjectiveAnswer',
                            verbose_name='主观题答案'
                        )),
                    ],
                    options={
                        'verbose_name': '主观题评分历史',
                        'verbose_name_plural': '主观题评分历史',
                        'ordering': ['-create_time'],
                    },
                ),
            ],
        ),
    ]
