# Generated by Codex on 2026-06-07

from django.db import migrations, models


def add_exam_time_columns(apps, schema_editor):
    table_name = 'exam_info'
    with schema_editor.connection.cursor() as cursor:
        existing = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'start_time' not in existing:
        schema_editor.execute(
            'ALTER TABLE "exam_info" ADD COLUMN "start_time" time NOT NULL DEFAULT "09:00"'
        )
    if 'end_time' not in existing:
        schema_editor.execute(
            'ALTER TABLE "exam_info" ADD COLUMN "end_time" time NOT NULL DEFAULT "11:00"'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_start_review_history'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_exam_time_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='exam',
                    name='start_time',
                    field=models.TimeField(default='09:00', verbose_name='开始时间'),
                ),
                migrations.AddField(
                    model_name='exam',
                    name='end_time',
                    field=models.TimeField(default='11:00', verbose_name='结束时间'),
                ),
            ],
        ),
    ]
